# Read a trusted initial-cache file without asking the shell to interpret CMake.
cmake_minimum_required(VERSION 3.14)

if(NOT DEFINED CONFIG_FILE OR NOT EXISTS "${CONFIG_FILE}")
    message(FATAL_ERROR "CONFIG_FILE must name an existing CMake configuration")
endif()
if(NOT DEFINED OUTPUT_DIR OR OUTPUT_DIR STREQUAL "")
    message(FATAL_ERROR "OUTPUT_DIR must name the metadata directory")
endif()
include("${CONFIG_FILE}")

# Capture whether the trusted configuration made an explicit MPI choice before
# loading CMake's default OFF. AUTO is CI policy, never a PLATFORM_MPI value.
if(DEFINED PLATFORM_MPI)
    string(TOUPPER "${PLATFORM_MPI}" mpi_mode)
    if(NOT mpi_mode MATCHES "^(ON|OFF)$")
        message(FATAL_ERROR "PLATFORM_MPI must be ON or OFF; omit it for automatic CI detection")
    endif()
else()
    set(mpi_mode AUTO)
endif()
if(DEFINED SCFD_CI_MPI)
    message(FATAL_ERROR "SCFD_CI_MPI was removed; use PLATFORM_MPI=ON/OFF or omit it for automatic CI detection")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/SCFDPlatform.cmake")

if(NOT DEFINED SCFD_CI_REQUIRED)
    if(PLATFORM STREQUAL "SERIAL" OR PLATFORM STREQUAL "OMP")
        set(SCFD_CI_REQUIRED ON)
    else()
        set(SCFD_CI_REQUIRED OFF)
    endif()
endif()
string(TOUPPER "${SCFD_CI_REQUIRED}" required)
if(NOT required MATCHES "^(ON|OFF)$")
    message(FATAL_ERROR "SCFD_CI_REQUIRED must be ON or OFF")
endif()

file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT_DIR}/platform.txt" "${PLATFORM}\n")
file(WRITE "${OUTPUT_DIR}/mpi_mode.txt" "${mpi_mode}\n")
file(WRITE "${OUTPUT_DIR}/required.txt" "${required}\n")
