# Read a trusted initial-cache file without asking the shell to interpret CMake.
cmake_minimum_required(VERSION 3.14)

if(NOT DEFINED CONFIG_FILE OR NOT EXISTS "${CONFIG_FILE}")
    message(FATAL_ERROR "CONFIG_FILE must name an existing CMake configuration")
endif()
if(NOT DEFINED OUTPUT_DIR OR OUTPUT_DIR STREQUAL "")
    message(FATAL_ERROR "OUTPUT_DIR must name the metadata directory")
endif()
include("${CONFIG_FILE}")

set(backend host)
set(accelerators 0)
foreach(platform CUDA HIP SYCL)
    if(SCFD_WITH_${platform})
        math(EXPR accelerators "${accelerators} + 1")
        string(TOLOWER "${platform}" backend)
    endif()
endforeach()
if(accelerators GREATER 1)
    message(FATAL_ERROR "Select only one accelerator per CI configuration")
endif()

if(NOT DEFINED SCFD_CI_MPI)
    if(backend STREQUAL "host")
        set(SCFD_CI_MPI AUTO)
    else()
        set(SCFD_CI_MPI OFF)
    endif()
endif()
string(TOUPPER "${SCFD_CI_MPI}" mpi_mode)
if(NOT mpi_mode MATCHES "^(AUTO|ON|OFF)$")
    message(FATAL_ERROR "SCFD_CI_MPI must be AUTO, ON, or OFF")
endif()
if(NOT backend STREQUAL "host")
    if(mpi_mode STREQUAL "ON")
        message(FATAL_ERROR "The current CMake MPI tests support host configurations only")
    endif()
    set(mpi_mode OFF)
endif()

if(NOT DEFINED SCFD_CI_REQUIRED)
    if(backend STREQUAL "host")
        set(SCFD_CI_REQUIRED ON)
    else()
        set(SCFD_CI_REQUIRED OFF)
    endif()
endif()
string(TOUPPER "${SCFD_CI_REQUIRED}" required)
if(NOT required MATCHES "^(ON|OFF)$")
    message(FATAL_ERROR "SCFD_CI_REQUIRED must be ON or OFF")
endif()

file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT_DIR}/backend.txt" "${backend}\n")
file(WRITE "${OUTPUT_DIR}/mpi_mode.txt" "${mpi_mode}\n")
file(WRITE "${OUTPUT_DIR}/required.txt" "${required}\n")
