# Select a suitable architecture in a machine-specific copy if needed, e.g.
# set(CMAKE_CUDA_ARCHITECTURES 75 CACHE STRING "CUDA architectures")
set(CMAKE_C_COMPILER gcc CACHE STRING "C compiler")
set(CMAKE_CXX_COMPILER g++ CACHE STRING "C++ compiler")
set(CMAKE_CUDA_COMPILER nvcc CACHE STRING "CUDA compiler")
set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type (keep assertions enabled)")
set(SCFD_WITH_CUDA ON CACHE BOOL "Build CUDA tests")
set(SCFD_WITH_HIP OFF CACHE BOOL "Build HIP tests")
set(SCFD_WITH_SYCL OFF CACHE BOOL "Build SYCL tests")
set(SCFD_CI_MPI OFF CACHE STRING "MPI capability policy: AUTO, ON, OFF")
set(SCFD_CI_REQUIRED OFF CACHE BOOL "Fail if this configuration is unavailable")
